name: E2E CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        app: ['angular-app', 'react-app', 'vue-app', 'svelte-app']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install monore dependencies
      run: npm ci
    - name: Build ${{matrix.app}}
      run: |
        cd ${{matrix.app}} 
        npm ci
        npm run build -- --prod
    - name: Run E2E compaign
      run: |
        npm run test:angular
        npm run test:vue
        npm run test:react
        npm run test:svelte
